accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'
urlpatterns = [
    path('', views.index, name="index"),
    path('category/<int:pk>/', views.product_category_list, name='product_category_list'),
    path('watchlist/', views.product_watchlist, name='product_watchlist'),
    path('add_product_watchlist/<int:pk>/', views.add_product_watchlist, name='add_product_watchlist'),
    path('remove_product_watchlist/<int:pk>/', views.remove_product_watchlist, name='remove_product_watchlist'),
    path('product_detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('end_product_bid/<int:pk>/', views.end_product_bid, name='end_product_bid'),
    path('start_product_bid/<int:pk>/', views.start_product_bid, name='start_product_bid'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auctions.urls')),
    path('accounts/', include('accounts.urls')),
]

auctions/models.py
from django.db import models
from django.shortcuts import reverse
from accounts.models import CustomUser
import uuid


class Category(models.Model):
    category_name = models.CharField(max_length=25, unique=True)

    def __str__(self):
        return self.category_name


class Product(models.Model):
    STATIC_CHOICES = (
        ('end', 'ending bid'),
        ('start', 'starting bid'),
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category')
    author = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='author_product')
    product_name = models.CharField(max_length=50, blank=False)
    description = models.TextField(blank=True)
    starting_bid = models.PositiveIntegerField(null=False, blank=False)
    image_url = models.URLField(null=True, blank=True)
    status = models.CharField(max_length=5, choices=STATIC_CHOICES, default='start')
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product_name

    def get_absolute_url(self):
        return reverse('auctions:product_detail', args=[self.id])


class Comment(models.Model):
    author = models.ForeignKey(CustomUser, models.CASCADE)
    caption = models.TextField(blank=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    product = models.ManyToManyField(Product, related_name='product_comment')

    def __str__(self):
        return f"{self.author} commented to {self.product.values('product_name')[0]['product_name']}"


class WinnerBid(models.Model):
    code = models.CharField(max_length=36, default=uuid.uuid4, unique=True)
    author = models.ForeignKey(CustomUser, models.CASCADE)
    product = models.ForeignKey(Product, models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)


class WatchList(models.Model):
    author = models.ForeignKey(CustomUser, models.CASCADE, related_name='user_watchlist')
    product = models.ManyToManyField(Product)
    date_created = models.DateTimeField(auto_now_add=True)

auctions/forms.py
from django.forms import ModelForm
from django import forms
from .models import Product, Comment


class AddProductForm(ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('author', 'status')


class BidForm(forms.Form):
    starting_bid = forms.IntegerField(min_value=1)


class AddCommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'
        exclude = ('author', 'product', 'date_created', 'date_modified',)

auctions/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import AddProductForm, BidForm, AddCommentForm
from .models import *


def index(request):
    products = Product.objects.all().order_by('-date_created')
    category = Category.objects.all()
    context = {
        'products': products,
        'category': category,
    }
    return render(request, 'index.html', context)


def product_category_list(request, pk):
    products = Product.objects.filter(category_id=pk).order_by('-date_created')
    category = Category.objects.get(id=pk)
    context = {
        'products': products,
        'category': category,
    }
    return render(request, 'auctions/product_category_list.html', context)


def add_product_watchlist(request, pk):
    try:
        watch = WatchList.objects.get(author_id=request.user.id)
        watch.product.add(pk)
    except WatchList.DoesNotExist:
        watch = WatchList.objects.create(author_id=request.user.id)
        watch.save()
        watch.product.add(pk)
    messages.success(request, 'watchlist successfully added')
    return redirect('auctions:product_detail', pk)


def product_watchlist(request):
    products = []
    if not request.user.is_authenticated:
        messages.warning(request, 'you are not login')
        return redirect('accounts:login')
    watch_lists = CustomUser.objects.get(id=request.user.id).user_watchlist.all()
    for watch in watch_lists:
        products.extend(watch.product.all())
    context = {
        'watch_lists': products,
    }
    return render(request, 'auctions/watchlist.html', context)


def product_detail(request, pk):
    product = Product.objects.get(id=pk)
    try:
        winner = WinnerBid.objects.get(product_id=pk)
    except WinnerBid.DoesNotExist:
        winner = None
    bid_form = BidForm(request.POST or None)
    comment_form = AddCommentForm()
    if bid_form.is_valid():
        bid = bid_form.cleaned_data['starting_bid']
        if bid < product.starting_bid:
            messages.error(request, f'your bid at the rate of {bid} is litter than {product.starting_bid}')
        else:
            product.starting_bid = bid
            request.session['user'] = request.user.id
            product.save()
            messages.success(request, f'your bid at the rate of {bid} was successfully registered.')
        return redirect(product.get_absolute_url())
    check_user_product = product.author.id == request.user.id
    try:
        check_watchlist_product = CustomUser.objects.get(id=request.user.id).user_watchlist.get(
            product=product).product.all()
    except WatchList.DoesNotExist:
        check_watchlist_product = False
    context = {
        'product': product,
        'bid_form': bid_form,
        'check': check_user_product,
        'check_watch': check_watchlist_product,
        'comment_form': comment_form,
        'winner': winner,
        'comments': product.product_comment.all(),
    }
    return render(request, 'auctions/product_detail.html', context)


def add_product(request):
    if not request.user.is_authenticated:
        messages.warning(request, 'you are not login')
        return redirect('accounts:login')
    form = AddProductForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.author = request.user
        instance.save()
        messages.success(request, 'product successfully added')
        return redirect('auctions:index')
    context = {
        'form': form,
    }
    return render(request, 'auctions/add_product.html', context)


def remove_product_watchlist(request, pk):
    product = Product.objects.get(id=pk)
    watch = WatchList.objects.get(author_id=request.user.id)
    watch.product.remove(product)
    messages.success(request, 'your watchlist is removed')
    return redirect(product.get_absolute_url())


def add_comment(request, pk):
    if not request.user.is_authenticated:
        messages.error(request, 'you must be logged in')
        return redirect('accounts:login')
    comment = AddCommentForm(request.POST)
    product = Product.objects.get(id=pk)
    if comment.is_valid():
        instance = comment.save(commit=False)
        instance.author = request.user
        instance.save()
        instance.product.add(product)
        messages.success(request, 'added comment successfully')
    return redirect(product.get_absolute_url())


def start_product_bid(request, pk):
    product = Product.objects.get(id=pk)
    product.status = 'start'
    product.save()
    WinnerBid.objects.filter(product_id=pk).delete()
    request.session['user'] = request.user.id
    messages.success(request, f'starting bid at {product.starting_bid}')
    return redirect(product.get_absolute_url())


def end_product_bid(request, pk):
    product = Product.objects.get(id=pk)
    if 'user' in request.session and request.session['user'] != request.user.id:
        winner = WinnerBid.objects.create(author_id=request.session['user'], product_id=product.id)
        winner.save()
    product.status = 'end'
    product.save()
    messages.success(request, f'ending bid at {product.starting_bid}')
    return redirect(product.get_absolute_url())

auctions/templates/auctions/add_product.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    add_post
{% endblock %}
{% block body %}
    <div class="container w-100">
        <div class="card container-fluid w-75 d-flex justify-content-center align-items-center shadow rounded p-4">
            <h2 class="mb-4">Add Product</h2>
            <form action="" class="w-50" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-primary w-100 mb-2">
            </form>
        </div>
    </div>
{% endblock %}

auctions/templates/auctions/product_category_list.html
{% extends '_base.html' %}
{% block title %}
    {{ category.category_name }}
{% endblock %}
{% block body %}
    <h2 class="mb-4">{{ category.category_name }} Listings</h2>
    <div class="row w100 h100">
        {% for product in products %}

            <div class="col-3 d-flex align-item-center justify-content-center">
                <div class="card">
                    <img src="{{ product.image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <p class="card-text">
                            {{ product.description }}
                        </p>
                        <div>
                            <small class="{% if product.status == 'end' %}text-danger{% else %}text-muted{% endif %}">
                                {% if product.status == 'end' %}
                                    ending bid --> {{ product.starting_bid }}$
                                {% else %}
                                    starting bid --> {{ product.starting_bid }}$
                                {% endif %}
                            </small>
                        </div>
                        <a href="{{ product.get_absolute_url }}"
                           class="d-flex justify-content-end text-decoration-none">
                            <button class="btn btn-outline-primary btn-sm">See Detail</button>
                        </a>
                    </div>

                    <div class="card-footer">
                        <small class="text-muted">Last updated --> {{ product.date_modified }}</small>
                    </div>
                </div>
            </div>


        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/product_detail.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    {{ product.product_name }}
{% endblock %}
{% block body %}
    <div class="d-flex justify-content-center mt-5">
        <div class="card mb-3 w-75 text-center shadow ">
            <img src="{{ product.image_url }}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{ product.product_name }}</h5>
                <p class="card-text">
                    {{ product.description }}
                </p>
                <div>
                    <small class="text-muted">
                        {% if product.status == 'end' %}
                            ending bid --> {{ product.starting_bid }}$
                        {% else %}
                            starting bid --> {{ product.starting_bid }}$
                        {% endif %}
                    </small>
                </div>
                {% if user.is_authenticated %}
                    {% if check %}
                        {% if product.status == 'start' %}
                            <a href="{% url 'auctions:end_product_bid' product.id %}"
                               class="text-decoration-none btn btn-outline-danger rounded m-3">ending bid</a>
                        {% else %}
                            <a href="{% url 'auctions:start_product_bid' product.id %}"
                               class="text-decoration-none btn btn-outline-success rounded m-3">starting bid</a>
                        {% endif %}
                    {% elif product.status == 'end' %}
                        {% if winner and winner.author_id == request.user.id %}
                            <p class="text-success m-2"><strong>You, the {{ winner.author.username }}, won the bid.
                                😁😁</strong>
                            </p>
                            <p class="text-muted">The product was purchased for {{ product.starting_bid }}$</p>
                        {% else %}
                            <div class="m-3">
                                <p class="text-danger m-2"><strong>The product tender has ended.</strong></p>
                                <p class="text-muted">The product was purchased for {{ product.starting_bid }}$</p>
                            </div>
                        {% endif %}
                    {% else %}
                        <form class="d-flex flex-column align-items-center justify-content-center m-3" action=""
                              method="post">
                            {% csrf_token %}
                            {{ bid_form|crispy }}
                            <input type="submit" class="btn btn-outline-success rounded">
                        </form>
                    {% endif %}
                {% else %}
                    <p class="text-danger m-3">You must be logged in to set an auction price --> <a
                            href="{% url 'accounts:login' %}">Login</a></p>
                {% endif %}

                <p class="card-text"><small class="text-muted">Last updated --> {{ product.date_modified }}</small></p>
                {% if user.is_authenticated %}
                    {% if check_watch %}
                        <a href="{% url 'auctions:remove_product_watchlist' product.id %}"
                           class="text-decoration-none btn btn-outline-danger rounded m-3">Remove to watchlist</a>
                    {% else %}
                        <a href="{% url 'auctions:add_product_watchlist' product.id %}"
                           class="text-decoration-none btn btn-outline-primary rounded m-3">Add to watchlist</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <div class="card mb-3 w-75 text-center shadow p-4">
            <h2 class="mb-3 text-secondary">Add Comment</h2>
            <form class="container-fluid w-50" action="{% url 'auctions:add_comment' product.id %}" method="post">
                {% csrf_token %}
                {{ comment_form|crispy }}
                <input type="submit" class="btn btn-outline-primary w-100">
            </form>
        </div>
    </div>
    <div class="d-flex justify-content-center mt-3">
        <div class="card mb-3 w-75 shadow p-4">
            {% if comments %}
                <h4 class="text-secondary text-center mb-4">Comments:</h4>
                {% for comment in comments %}
                    <div class="d-flex flex-column align-items-center">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png"
                             class="object-fit-scale shadow rounded-circle mb-2" alt="..." style="width: 100px">
                        <p>
                            {{ comment.author.username }}
                        </p>
                        <p class="mb-2">
                            <small class="text-primary">{{ comment.caption }}</small>
                        </p>
                        <p>
                            <small class="text-muted">created --> {{ comment.date_created }}</small>
                        </p>
                    </div>
                    <hr>
                {% endfor %}
            {% else %}
                {% for comment in comments %}
                    <div class="d-flex flex-column">
                        <img src="https://upload.wikimedia.org/wikipedia/commons/9/99/Sample_User_Icon.png"
                             class="rounded-start object-fit-scale shadow rounded mb-2" alt="..." style="width: 100px">
                        <p>
                            no username
                        </p>
                        <p class="mb-2">
                            <small class="text-primary">no caption</small>
                        </p>
                        <p>
                            <small class="text-muted">created --> no date_created</small>
                        </p>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
    </div>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends '_base.html' %}
{% block title %}
    Watch List
{% endblock %}
{% block body %}
    <h2 class="mb-4">Active Listings</h2>
    <div class="row w100 h100">
        {% for product in watch_lists %}
            <div class="col-3 d-flex align-item-center justify-content-center">
                <div class="card">
                    <img src="{{ product.image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <p class="card-text">
                            {{ product.description }}
                        </p>
                        <div>
                            <small class="{% if product.status == 'end' %}text-danger{% else %}text-muted{% endif %}">
                                {% if product.status == 'end' %}
                                    ending bid --> {{ product.starting_bid }}$
                                {% else %}
                                    starting bid --> {{ product.starting_bid }}$
                                {% endif %}
                            </small>
                        </div>
                        <a href="{{ product.get_absolute_url }}"
                           class="d-flex justify-content-end text-decoration-none">
                            <button class="btn btn-outline-primary btn-sm">See Detail</button>
                        </a>
                    </div>

                    <div class="card-footer">
                        <small class="text-muted">Last updated --> {{ product.date_modified }}</small>
                    </div>
                </div>
            </div>


        {% endfor %}
    </div>
{% endblock %}