accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register")
]

auctions/urls.py
from django.urls import path

from . import views

app_name = 'auctions'
urlpatterns = [
    path('', views.index, name="index"),
    path('category/<int:pk>/', views.product_category_list, name='product_category_list'),
    path('watchlist/', views.product_watchlist, name='product_watchlist'),
    path('add_product_watchlist/<int:pk>/', views.add_product_watchlist, name='add_product_watchlist'),
    path('remove_product_watchlist/<int:pk>/', views.remove_product_watchlist, name='remove_product_watchlist'),
    path('product_detail/<int:pk>/', views.product_detail, name='product_detail'),
    path('add_product/', views.add_product, name='add_product'),
    path('end_product_bid/<int:pk>/', views.end_product_bid, name='end_product_bid'),
    path('start_product_bid/<int:pk>/', views.start_product_bid, name='start_product_bid'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('auctions.urls')),
    path('accounts/', include('accounts.urls')),
]

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Auctions{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body class="p-3">
{% include 'messages.html' %}
<h1>Auctions</h1>
<div>
    {% if user.is_authenticated %}
        Signed in as <strong>{{ user.username }}</strong>.
    {% else %}
        Not signed in.
    {% endif %}
</div>

<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:add_product' %}">Add Product</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'auctions:product_watchlist' %}">Watchlist</a>
    </li>
    <li>
        <div class="dropdown">
            <button class="btn btn-secondary text-primary dropdown-toggle" type="button" id="dropdownMenuButton"
                    data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false" style="background-color: white; border: none">
                Category
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                {% for category in categories %}
                    <a class="dropdown-item"
                       href="{% url 'auctions:product_category_list' category.id %}">{{ category }}</a>
                {% endfor %}

            </div>
        </div>
    </li>
    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
    {% endif %}
</ul>
<hr>
{% block body %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "_base.html" %}
{% block title %}
    products
{% endblock %}
{% block _category %}
    <div class="dropdown">
        <button class="btn btn-secondary text-primary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false" style="background-color: white; border: none">
            Category
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            {% for cat in category %}
                <a class="dropdown-item" href="">{{ cat.category_name }}</a>
            {% endfor %}
        </div>
    </div>
{% endblock %}
{% block body %}
    <h2 class="mb-4">Active Listings</h2>
    <div class="row w100 h100">
        {% for product in products %}

            <div class="col-3 d-flex align-item-center justify-content-center">
                <div class="card">
                    <img src="{{ product.image_url }}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ product.product_name }}</h5>
                        <p class="card-text">
                            {{ product.description }}
                        </p>
                        <div>
                            <small class="{% if product.status == 'end' %}text-danger{% else %}text-muted{% endif %}">
                                {% if product.status == 'end' %}
                                    ending bid --> {{ product.starting_bid }}$
                                {% else %}
                                    starting bid --> {{ product.starting_bid }}$
                                {% endif %}
                            </small>
                        </div>
                        <a href="{{ product.get_absolute_url }}"
                           class="d-flex justify-content-end text-decoration-none">
                            <button class="btn btn-outline-primary btn-sm">See Detail</button>
                        </a>
                    </div>

                    <div class="card-footer">
                        <small class="text-muted">Last updated --> {{ product.date_modified }}</small>
                    </div>
                </div>
            </div>


        {% endfor %}
    </div>

{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %} fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}